### PR TITLE
Moving auto-sync settings to settings (Fixes #71)

### LINKED ISSUE #71: sync button and sync setting on login screen
An issue was brought up in https://github.com/ole-vi/takeout/pull/65#issuecomment-397030934 and https://github.com/ole-vi/takeout/pull/65#issuecomment-397309669.

### PR DESCRIPTION
**Pull request by aakarnik**
Fixes #71 

I finished fixing a part of the above issue: moving the settings from the Sync button to the Settings button.

Screenshots:

[5.5in-landscape](https://user-images.githubusercontent.com/37878201/41869565-62eab66c-7887-11e8-9ec4-3a6383f2d2e1.jpg)
[5.5in-portrait](https://user-images.githubusercontent.com/37878201/41869567-63029c96-7887-11e8-907f-9899b070d574.jpg)

[10in-landscape](https://user-images.githubusercontent.com/37878201/41869633-99d33640-7887-11e8-956a-be695333c1bd.png)
[10in-portrait](https://user-images.githubusercontent.com/37878201/41869636-99e9fe0c-7887-11e8-8492-c6f4bef73a4d.png)

### CODE REVIEW

**Comment by aakarnik** [comment]
I am trying to implement a gif button using https://github.com/koral--/android-gif-drawable

**Comment by leomaxi** [comment]
@aakarnik , Good work.. Looking good so far. Let me know when you need any help.

**Comment by aakarnik** [comment]
[10in-portrait](https://user-images.githubusercontent.com/37878201/42102443-e8434806-7b93-11e8-81ca-d35fa8c8b6c0.png)
[10in-landscape](https://user-images.githubusercontent.com/37878201/42102444-e857f0b2-7b93-11e8-8be8-a2b8b5ce629a.png)
[5.5in-portrait](https://user-images.githubusercontent.com/37878201/42102445-e8b74ab2-7b93-11e8-90bd-8f715ec89f7c.jpg)
[5.5in-landscape](https://user-images.githubusercontent.com/37878201/42102446-e8d36a1c-7b93-11e8-9590-4e5df60f0299.jpg)

Fixed #96 
- Sync icon is now a GifImageButton which rotates on clicking
- The AutoSync settings are moved into a Settings menu

**Comment by leomaxi** [comment]
👍🏿

**Pull request merged**
