### PR TITLE
textview clickable fixes#90

### PR DESCRIPTION
**Pull request by akshayuncc**
Making all the textViews clickable and pointing to an intent.
(Changed the names of all the textViews and made them clickable).

**
Currently I was testing hence the authentication is disabled but in my next PR i will correct it.

### CODE REVIEW

**Comment by xyb994** [comment]
@akshayuncc I looked at the commit history for this branch, looks like it branched from `makingImageButtonClickable ` instead of master. All the changes in PR #89 is also in here. Please try to resolve this.

**Comment by akshayuncc** [comment]
@xyb994 this PR has the the same changes because it come after the other PR. You could merge that PR then there wont be any conflicts. Also I created a new PR so you can ignore this if you want and just merge the new one. 
If you merge this then you could see the changes in the one i just made .

**Comment by xyb994** [comment]
@aakarnik That's not how things normally works. Just like you were creating separate branches to solve difference issues when you are doing first steps, we isolate issues...

**Comment by akshayuncc** [comment]
The issue need a little bit more work to solve the issue.

**Pull request closed without merging**
