### PR TITLE
Dashboard screen sizes ( fixes #41 , #48)

### LINKED ISSUE #41: dashboard does not display correctly on smaller screen size and portrait mode
See screenshot and description at https://github.com/ole-vi/takeout/pull/31#issuecomment-391455488

### PR DESCRIPTION
**Pull request by aakarnik**
Reference: #41 

Working on landscape mode currently. I tested two screen sizes:
Moto G4 - 5.5in screen

The icons look very small on the phone screen. On scaling, they look pixelated. 
What approach should I use there?

10in Tablet
The xlarge, large, and default landscape layout have the same look.

I removed the icons from the small landscape layout so that the text is displayed clearly.

Also, I am not able to view the profile picture - the message says that the file is empty.

Anything I should add/change?

### CODE REVIEW

**Comment by xyb994** [comment]
@aakarnik here are some screenshots:
[10-inch-1280x800-portrait](https://user-images.githubusercontent.com/7483137/40806398-576752ec-64ef-11e8-8d95-3d0f670c9697.png)
[5 7-inch-1440x2560-portrait](https://user-images.githubusercontent.com/7483137/40806399-5775af4a-64ef-11e8-9f54-e51ad4f20575.png)
[5 7-inch-1440x2560-landscape](https://user-images.githubusercontent.com/7483137/40806400-5786fba6-64ef-11e8-8e96-2c67dbdcacdc.png)
[10-inch-1920x1200-portrait](https://user-images.githubusercontent.com/7483137/40806402-579dc3fe-64ef-11e8-82ac-de32663be2f2.png)

**Comment by aakarnik** [comment]
10in Portrait
10in Landscape

Is there anything that needs to be adjusted?

**Comment by dogi** [comment]
@leomaxi and @aakarnik 5.5in or 5.7in I am confused ;)

**Comment by leomaxi** [comment]
Thanks @dogi , Both are the same dpi..

**Comment by xyb994** [comment]
It looks better now :)

Only issue I see it that  name would not fully display in
[portrait mode (10 inch 800*1280)](https://user-images.githubusercontent.com/7483137/40938672-7de04fae-6810-11e8-8b3c-119bfe444802.png), this is potentially a problem since a lot of people have even longer names. @aakarnik Have you thought about a little design tweak to the left side name card to accommodate longer names?

**Comment by aakarnik** [comment]
@xyb994 I actually changed the height constraint for the field to 'wrap content' and it worked for the 10in virtual device I am using.

**Comment by aakarnik** [comment]
I have changed the height of the TextField to `wrap content` which should accommodate any length of a name.

**Pull request merged**
