### PR TITLE
removing add back stack

### LINKED ISSUE #94: addToBackStack issue
Every time we click the back button from the dashboardFragment we are pointed back to the empty fragment of dashboard.

Solution:
Remove the addToBackStack .

### PR DESCRIPTION
**Pull request by akshayuncc**
fixes #94

### CODE REVIEW

**Comment by xyb994** [comment]
@akshayuncc [The change](https://github.com/ole-vi/takeout/pull/95/files) seem to be not related to issue #94, could you check the code? Also `removingAddBackStack` looks identical to `textViewClickable` branch, make sure to branch from `master` branch.

**Comment by akshayuncc** [comment]
@xyb994 you are correct it did not show the changes in this PR will delete this and generate another one.
Thank you.

**Comment by xyb994** [comment]
@aakarnik the proper way of solving #94 is create a new branch from `master` and the only change we see would be removing `fragmentTransaction.addToBackStack(null);`.

**Comment by akshayuncc** [comment]
@xyb994 Sorry could you explain me the steps or a link i should follow?
What i do is i cd into takeout (Which i have git cloned)
then create a new branch using git checkout new_branch_name
then
git add .
git commit -m "message"
git push -u origin new_branch_name

Am I missing a step?
Thank you

**Comment by xyb994** [comment]
@akshayuncc need do `git checkout master` and `git pull` before `git checkout new_branch_name`

**Comment by leomaxi** [comment]
@akshayuncc , Follow @xyb994 direction above and create a new PR.. Closing this one

**Pull request closed without merging**
