### PR TITLE
learner dashboard

### PR DESCRIPTION
**Pull request by leomaxi**

### CODE REVIEW

**Comment by xyb994** [comment]
[OLE tablet landscape with drawer open](https://user-images.githubusercontent.com/7483137/40322208-9d3bdbfa-5cff-11e8-8c8d-a1cddad35aed.png) | [OLE tablet landscape](https://user-images.githubusercontent.com/7483137/40322209-9d49e47a-5cff-11e8-9891-4c20f42aa961.png)
Will this Android app include manager features? Looks like the people icon used is for managers. It's also a bit oversized.

Drawer's item position looks a bit weird after removing account info. Consider adding a placeholder things or move items down a little?

**Comment by xyb994** [comment]
[OLE tablet portrait mode](https://user-images.githubusercontent.com/7483137/40443945-dd111a8c-5e95-11e8-9de8-7946f60a8408.png)
[nexus 6p(5.7″ 2560×1440 515dpi) landscape mode](https://user-images.githubusercontent.com/7483137/40444008-1ea02024-5e96-11e8-8a06-0580689855fd.png)

Looks all good in landscape mode on OLE tablet, might need some change for portrait mode.

**Comment by xyb994** [comment]
Some design we could consider to borrow for the drawer top part?
[app-1](https://user-images.githubusercontent.com/7483137/40444574-bac1ff30-5e97-11e8-9aa6-dd5e860fac80.png) | [app-1-drawer](https://user-images.githubusercontent.com/7483137/40444573-baa8bf52-5e97-11e8-93e5-70ad365dbb2b.png)
[app-2](https://user-images.githubusercontent.com/7483137/40444571-ba8d7148-5e97-11e8-98f6-702a238bb29b.png) | [app-2-drawer](https://user-images.githubusercontent.com/7483137/40444572-ba9bda6c-5e97-11e8-8b23-b39d610783a7.png)

@aakarnik Do you have any thoughts on this?

**Comment by leomaxi** [comment]
I like this one https://user-images.githubusercontent.com/7483137/40444572-ba9bda6c-5e97-11e8-8b23-b39d610783a7.png .. Will look into implementing it

**Comment by aakarnik** [comment]
I agree with @leomaxi - the second one will go better with the overall theme of the dashboard.

**Pull request merged**
