### PR TITLE
adding fragments to navigation drawer (fixes 125)

### PR DESCRIPTION
**Pull request by akshayuncc**
fixes issue 125

### CODE REVIEW

**Comment by rrijal53** [comment]
Please try to reduce the line of code. Is this comparison is necessary ??
screen shot 2018-07-19 at 8 22 49 am

You can directly call openCallFragment method  from menu action method.
eg. 
` case R.string.menu_library:
     openCallFragment(new MyLibraryFragment()) ; 
     break;
`

**Comment by akshayuncc** [comment]
@rrijal53 Hi, I will explain when i attend the next meeting. Not feeling well currently.
You can in the mean while go ahead and implement it by calling the openCallFragment().
Regards,
Akshay

**Comment by akshayuncc** [comment]
@rrijal53 Hi, I will update the PR. Thanks.

**Comment by akshayuncc** [comment]
Seems to have some issue with travis-ci. Updated a it with a new PR.

**Pull request closed without merging**
