### PR TITLE
made all the imagebutton clickable (Fixes #88)

### LINKED ISSUE #88: make all the imagebuttons on the dashboard clickable
currently only one image myLibraryImageButton is clickable and is pointing to a new intent.
Make all the rest clickable.

### PR DESCRIPTION
**Pull request by akshayuncc**
Fixes #88

Currently the imageButtons are pointing to only the PDFreader.class . It is another issue.
I will generate another PR addressing that issue in a few minutes.

Thank you

### CODE REVIEW

**Comment by leomaxi** [comment]
@akshayuncc ,Can you fix the code climate issues?

**Comment by xyb994** [comment]
@akshayuncc I assume `!` [was added](https://github.com/ole-vi/takeout/pull/89/files#diff-131bbe720bda047a9206b8e02aec81a4R132) by accident or you were trying to see things without logging in? use `demo` `demo` as login should work.

**Comment by akshayuncc** [comment]
@leomaxi I dont know how to fix code climate . Have not done it before

**Comment by akshayuncc** [comment]
@xyb994 I fixed that in my next PR and I did mention that as well. I had it for testing.

**Comment by xyb994** [comment]
@leomaxi Where are "buttons" like myLibrary going to? Currently it's not going anywhere in web version of planet or BeLL. It's only scrollable, but I do think a separate interface is good.

**Comment by leomaxi** [comment]
@xyb994 , those buttons will go to a `listview` of all its corresponding content.

**Pull request merged**
