### PR TITLE
Logo Colour (Fixed issue 3 )

### PR DESCRIPTION
**Pull request by leomaxi**

### CODE REVIEW

**Comment by Going-Gone** [comment]
image

This is on the 7" tablet of mine. Otherwise looks good!

**Comment by kylemathias** [comment]
Galaxy s7
screenshot_20180416-104812

**Comment by lorugant** [comment]
screenshot 35

It shows up as such

**Comment by xyb994** [comment]
[ole_tablet](https://user-images.githubusercontent.com/7483137/38837786-4f11961e-41a1-11e8-8973-6b58fcbee915.png) | [phone](https://user-images.githubusercontent.com/7483137/38837787-4f1f9c28-41a1-11e8-89d7-5faa2a0dd355.png)

**Comment by lorugant** [comment]
screenshot 36

On my Lenovo phone

**Pull request merged**
