### PR TITLE
Fixing Takeout App drawer

### LINKED ISSUE #43: better drawer
Currently drawer items' icon color does not look right, 

drawer-icon-color

Can we change the color of these icon when a drawer item is selected?

### PR DESCRIPTION
**Pull request by aakarnik**
Fixes #43 

I was able to fix the color of the icons in the drawer. Will make changes if I find a better way to do it :)
I will also work on what can be added to the header section of the drawer.

[Screenshot - 5.5in portrait](https://user-images.githubusercontent.com/37878201/41250079-e9e91c62-6d83-11e8-81b6-5d6e6dd66992.jpg)

### CODE REVIEW

**Comment by xyb994** [comment]
Any particular reason for the spacing change? Try `Control + Alt + L` to reformat the code.

https://github.com/ole-vi/takeout/pull/68/files#diff-7b0d5ad0ef3493d2315751c168dc5e7fR105
 https://github.com/ole-vi/takeout/pull/68/files#diff-7b0d5ad0ef3493d2315751c168dc5e7fR47
https://github.com/ole-vi/takeout/pull/68/files#diff-7b0d5ad0ef3493d2315751c168dc5e7fR162

**Comment by aakarnik** [comment]
@xyb994 The spacing is different only because of editing the code a lot. I am still trying to figure out if there is a particular method that could make the code more efficient. I will also try the reformatting option with that :)

**Comment by xyb994** [comment]
@aakarnik Ok, thanks for the update, I add the label "in progress". You can also let the team to take a look at this

**Comment by aakarnik** [comment]
@xyb994 @leomaxi Reformatting the code did not work with code climate. I found a [similar issue](https://github.com/codeclimate/codeclimate-duplication/issues/290) posted in the code climate organization - as of 2017, they didn't seem to have a solution for that.

**Comment by leomaxi** [comment]
No worries @aakarnik

**Pull request merged**
